version: '3'

services:
  database:
    image: postgres:15-alpine
    restart: on-failure
    environment:
      POSTGRES_DB: test
      POSTGRES_USER: sf_user
      POSTGRES_PASSWORD: random_password
      PGDATA: /var/lib/postgresql/data
    volumes:
      - db-data:/var/lib/postgresql/data:rw
    ports:
      - "5432:5432"
volumes:
  db-data:
  var:











#version: '3'
#
#services:
####> doctrine/doctrine-bundle ###
#  database:
#    image: postgres:${POSTGRES_VERSION:-15}-alpine
#    environment:
##      POSTGRES_DB: ${POSTGRES_DB:-app}
#      POSTGRES_DB: db_desafio
#      # You should definitely change the password in production
##      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-!ChangeMe!}
#      POSTGRES_PASSWORD: db_desafio
##      POSTGRES_USER: ${POSTGRES_USER:-app}
#      POSTGRES_USER: postgres
#    ports:
#      - 5432:5432
#
#    volumes:
#      - database_data:/var/lib/postgresql/data:rw
#      # You may use a bind-mounted host directory instead, so that it is harder to accidentally remove the volume and lose all your data!
#      # - ./docker/db/data:/var/lib/postgresql/data:rw
####< doctrine/doctrine-bundle ###
#
#volumes:
####> doctrine/doctrine-bundle ###
#  database_data:
####< doctrine/doctrine-bundle ###
